version: "3.5"

x-environment:
  &default-back-environment
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: fndn*J%TiDUPf5
  POSTGRES_HOST: taiga-db
  TAIGA_SECRET_KEY: "2A!Xf7tp#M9s8e"
  # these rabbitmq settings should be the same as
  # in taiga-rabbitmq and taiga-events services
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: Nz7GRSrs4*ZF8s
  CELERY_ENABLED: "True"

x-volumes:
  &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-manage:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    depends_on:
      - taiga-db
    entrypoint: "python manage.py"
    volumes: *default-back-volumes
    networks:
      - taiga
